name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      [opened, synchronize]

env:
  MONGODB_TEST_URI: ${{secrets.MONGODB_TEST_URI}}
  MONGODB_URI: ${{secrets.MONGODB_URI}}
  PORT: ${{secrets.PORT}}
  TOKEN_SECRET: ${{secrets.TOKEN_SECRET}}

jobs:
  deployment_pipeline:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: npm install
        run: npm install
      - name: lint
        run: npm run lint
      - name: test
        run: npm test
      - name: E2E test
        uses: cypress-io/github-action@v2
        with:
          start: npm run start:test
      - name: Deploy to Heroku
        if: ${{ github.event_name == 'push' && !contains( join( github.event.commits.*.message ), '#skip') }}
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: misty-morning124
          heroku_email: ville.turku99@gmail.com
          healthcheck: https://misty-morning124.herokuapp.com/
          rollbackonhealthcheckfailed: true
      - name: slack-success
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo, message, commit, author, took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if:
          github.event_name == 'push' && !contains( join( github.event.commits.*.message ), '#skip') && success()
      - name: slack-failure-build
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo, message, commit, author, took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if:
          failure()
  version_tag:
    if: ${{ github.event_name == 'push' && !contains( join( github.event.commits.*.message ), '#skip') }}
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Bump version and push tag
        if: ${{ github.event_name == 'push' && !contains( join( github.event.commits.*.message ), '#skip') }}
        uses: anothrNick/github-tag-action@1.33.0
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          DEFAULT_BUMP: patch
          RELEASE_BRANCHES: main
      - name: slack-failure-tag
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo, message, commit, author, took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if:
          failure()